LOCAL_CPPFLAGS=$(CPPFLAGS)
LOCAL_CFLAGS=$(CFLAGS)
LOCAL_CXXFLAGS=$(CXXFLAGS)
LOCAL_LDFLAGS=$(LDFLAGS)
LOCAL_LIBADD=$(LIBADD)

LOCAL_CPPFLAGS+=-I${R} -I. -I${R}/include -I${R}/common
LOCAL_CFLAGS+=-fPIC
LOCAL_LDFLAGS+=-shared $(LOCAL_CFLAGS)
